### ISSUE TITLE
Branch name not configurable

### ISSUE THREAD

**Issue by MrASayles** [ccntrq/git-jira-branch#444]
As and SRE I would like to be able to have branches start with "task/". Even better would be for the branch type to be derived from the Jira ticket catagory (ie ticket categories like task, story, spike).

My company also also prefers, and monitors, PRs to have brackets around the ticket like [DEV-111].

Request is add environment parameter that allows these customizations.
JIRA_DEFAULT_TICKET_TYPE="task"
JIRA_TICKET_ENCAPSULATION="brackets || parenthesis || braces"

**Comment by ccntrq** [comment]
I added a flag `--type` to the create command in [https://github.com/ccntrq/git-jira-branch/releases/tag/git-jira-branch-v2.1.0](v2.1.0). 

You can use it like so: 

```
git-jira-branch create --type task 6543
```

I also updated the ticket type to branchtype mapping. Issues with a type containing `aufgabe` or `task` will now be mapped to a `task/` branch.

**Comment by MrASayles** [comment]
Confirmed working for me. Thank you!
`git-jira-branch create 587
Successfully created branch: 'task/DO-587-iva...'`
