### ISSUE TITLE
Allow for blank -t option on "create

### ISSUE THREAD

**Issue by tfalkarkea** [ccntrq/git-jira-branch#522]
Excited to have this tool, but my use-case doesn't appear to mesh. Our branches are named simply after the issue name, e.g. I would hope `git-jira-branch create 3262` would create a branch called `XXX-3262-automatically-delete-user-feedback`. Supplying an empty or blank string to `-t` creates an invalid branch name, `/XXX-3262-automatically-delete-user-feedback`.

Would it be possible to have an empty `-t` flag create a valid branch name with no leading branch type? Or another flag to enable such a thing.

**Comment by ccntrq** [comment]
Hey @tfalkarkea 

Thanks for your feedback. Sure that's possible. I'd even say it's the sensible thing to do when giving an empty branch type. Branches starting with a slash don't seem very useful to me. 

I will be travelling for the next month and won't be able to work on this before December. If you would like to have a go at it yourself I would be able to review and merge it, and create a release.

**Comment by ccntrq** [comment]
Has been released in [v2.2.0](https://github.com/ccntrq/git-jira-branch/releases/tag/git-jira-branch-v2.2.0)
